version: '2.3'

services:

  nsq:
    image: nsqio/nsq
    restart: always
    volumes:
      - ./keys:/keys:ro
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --tls-cert /keys/cert.pem --tls-key /keys/key.pem
    depends_on:
      - nsqlookupd

  nsqwithauth:
    image: nsqio/nsq
    restart: always
    command: /nsqd --auth-http-address=nsqauth:8080
    depends_on:
      - nsqauth

  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd

  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd

  nsqauth:
    image: node
    working_dir: "/app"
    restart: always
    volumes:
      - .:/app:ro
    command: node auth.js

  dev:
    image: rust
    working_dir: "/app"
    user: "${UID}:${GID}"
    volumes:
      - .:/app:rw
